name: ProjectsBas
version: '${project.version}'
main: com.zyneonstudios.nerotvlive.projectsbase.Main
api-version: 1.21
authors: [ nerotvlive, DerFantastico, Black_0mega ]
description: The base of Zyneon projects.

commands:
  weapon:
    aliases: [weapons]
  item:
    aliases: [getitem,customitem,getcustomitem,itemget,customitemget]
  author:
    aliases: [project,projects,projectsbase,zyneon,pb,pb5,projectsbase5]
  book:
    aliases: [buch,writable,feder,feather]
  broadcast:
    aliases: [bc,alert]
  character:
    aliases: [char,chareditor,charactereditor,editor,ceditor,name,job,rpname,rpjob,charakter]
  clearchat:
    aliases: [chatclear,cc,clearc,chatc]
  day:
  feed:
  fix:
  mute:
  voicemute:
  fly:
  gamemode:
    aliases: [gm,spielmodus,sm]
  god:
  heal:
  invsee:
  maintenance:
  night:
  rain:
  roleplay:
    aliases: [rp,erpe,offrp,ooc]
  say:
  shout:
    aliases: [s,schreien]
  speed:
  srl:
    aliases: [stop,srs,serverstop,serverrestart,serverreload,restart,rl,rs,reload,end]
  sun:
  team:
    aliases: [teammode]
  tell:
    aliases: [t,m,msg]
  thunder:
  warp:
    aliases: [spawn]
  whisper:
    aliases: [w,f,flüstern]
  whitelist:
    aliases: [list,white-list]
  world:
    aliases: [welt,map,karte]
  skin:
  search:
  reply:
    aliases: [r,answer,a,antworten,antwort,antworte]